version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - redis
      - postgres
    command: celery -A yourapp worker --loglevel=info
