version: '3.8'
services:
  app:
    build: .
    command: "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_PSQL} -d ${PASS_PSQL}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      POSTGRES_USER: ${USER_PSQL}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${PASS_PSQL}
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    build: .
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker -l INFO
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
