# Generated by Django 4.2.4 on 2023-10-04 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_habit_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 4, 19, 1, 48, 595239, tzinfo=datetime.timezone.utc), verbose_name='время выполнения'),
        ),
    ]
