# Generated by Django 4.2.4 on 2023-10-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default='00-00-00', verbose_name='время выполнения'),
        ),
    ]
